In [10]:
import numpy as np

In [11]:
A = np.array([
    [3, 0],
    [1, 2]
])

B = np.array([
    [2, 1],
    [0, 3]
])

## Equilíbrios "puros"

In [12]:
# Resolvendo "na marra"

equilibrios = []

for i in range(A.shape[0]):
    for j in range(A.shape[1]):

        melhor_j1 = A[i, j] == np.max(A[:, j])
        melhor_j2 = B[i, j] == np.max(B[i, :])

        if melhor_j1 and melhor_j2:
            equilibrios.append((i, j))

print(equilibrios)

[(0, 0), (1, 1)]


## Equilíbrios "mistos"

In [13]:
import sympy as sp

# Variáveis simbólicas
p, q = sp.symbols('p q')


# Estratégias mistas (vetores linha)
prob1 = sp.Matrix([[p, 1-p]])
prob2 = sp.Matrix([[q, 1-q]])

# Payoffs esperados
payoff1 = (prob1 * A * prob2.T)[0]
payoff2 = (prob1 * B * prob2.T)[0]

# Simplificar/expandir as expressões
payoff1 = sp.collect(sp.expand(payoff1),p)
payoff2 = sp.collect(sp.expand(payoff2),q)


print("Payoff esperado do Jogador 1:")
print(payoff1)

print()

print("Payoff esperado do Jogador 2:")
print(payoff2)

print()

# Payoff do Jogador 1 se escolher linha 1
prob1_L1 = sp.Matrix([[1, 0]])
U1_L1 = (prob1_L1 * A * prob2.T)[0]
print('Payoff do Jogador 1 se escolher linha 1')
print(U1_L1)

# Payoff do Jogador 1 se escolher linha 2
prob1_L2 = sp.Matrix([[0, 1]])
U1_L2 = (prob1_L2 * A * prob2.T)[0]
print('Payoff do Jogador 1 se escolher linha 2')
print(U1_L2)
print()

# Payoff do Jogador 2 se escolher coluna 1
prob2_C1 = sp.Matrix([[1, 0]])
U2_C1 = (prob1 * B * prob2_C1.T)[0]
print('Payoff do Jogador 2 se escolher coluna 1')
print(U2_C1)

# Payoff do Jogador 2 se escolher coluna 2
prob2_C2 = sp.Matrix([[0, 1]])
U2_C2 = (prob1 * B * prob2_C2.T)[0]
print('Payoff do Jogador 2 se escolher coluna 2')
print(U2_C2)
print()

eq1 = sp.Eq(U1_L1, U1_L2)
eq2 = sp.Eq(U2_C1, U2_C2)

print("Indiferença do Jogador 1:")
print(eq1)

print("Indiferença do Jogador 2:")
print(eq2)
print()
solucao = sp.solve([eq1, eq2], [p, q])

print('Solução: equilíbrio misto')
print(solucao)

Payoff esperado do Jogador 1:
p*(4*q - 2) - q + 2

Payoff esperado do Jogador 2:
-2*p + q*(4*p - 3) + 3

Payoff do Jogador 1 se escolher linha 1
3*q
Payoff do Jogador 1 se escolher linha 2
2 - q

Payoff do Jogador 2 se escolher coluna 1
2*p
Payoff do Jogador 2 se escolher coluna 2
3 - 2*p

Indiferença do Jogador 1:
Eq(3*q, 2 - q)
Indiferença do Jogador 2:
Eq(2*p, 3 - 2*p)

Solução: equilíbrio misto
{p: 3/4, q: 1/2}


In [14]:
import nashpy as nash
import numpy as np

A = np.array([
    [3, 0],
    [1, 2]
])

B = np.array([
    [2, 1],
    [0, 3]
])

jogo = nash.Game(A, B)

equilibrios = list(jogo.support_enumeration())

for eq in equilibrios:
    print(eq)

(array([1., 0.]), array([1., 0.]))
(array([0., 1.]), array([0., 1.]))
(array([0.75, 0.25]), array([0.5, 0.5]))
